name: Build Package
on: [push]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: 'Perl Build'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.30'
      - run: cpan install -y File::Copy::Recursive
      - run: perl Makefile.PL
      - run: make dist
