name: Build Package
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: 'Perl Build'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.30'
      - run: perl Makefile.PL
      - run: make dist

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            Netkit*.tar.gz
